---
pihole_compose_dir: ""
# Host paths below are bind-mounted to Pi-hole's expected container paths.
# - {{ pihole_data_dir }} -> /etc/pihole
# - {{ pihole_dnsmasq_dir }} -> /etc/dnsmasq.d
pihole_data_dir: ""
pihole_dnsmasq_dir: ""
pihole_uid: ""
pihole_gid: ""
# Pin the image tag for repeatable deployments.
# Bump intentionally when upgrading.
pihole_image: ""
pihole_timezone: ""
pihole_web_port: ""
pihole_web_password: ""
pihole_network_mode: ""
pihole_dns1: ""
pihole_dns2: ""
pihole_local_ipv4: ""
pihole_enable_dhcp: ""
pihole_dnsmasq_listening: ""
pihole_healthcheck_enabled: ""
pihole_report_email: ""
pihole_report_sender: ""
pihole_report_smtp_host: ""
pihole_report_smtp_port: ""
pihole_report_smtp_user: ""
pihole_report_smtp_password: ""
pihole_report_schedule: ""
pihole_report_api_token: ""
pihole_report_mode: ""
pihole_container_name: ""
pihole_api_password: ""
pihole_api_max_sessions:
pihole_systemd_autostart: ""
pihole_sync_enabled:
pihole_sync_primary_url: ""
pihole_sync_interval:
pihole_sync_backoff_seconds:
pihole_sync_image: ""
pihole_sync_password: ""
pihole_sync_local_api: ""
pihole_sync_verify:
pihole_sync_verify_delay:
pihole_traefik_enabled: false
pihole_traefik_network: "web"
pihole_traefik_host: ""
pihole_traefik_entrypoints: "websecure"
pihole_traefik_tls: true
pihole_traefik_router: "pihole"
